name: Build and Release
run-name: Build artifacts and docker images for all platforms
on: [push]

jobs:
    release:
        name: Release - ${{ matrix.platform.os-name }}
        strategy:
            matrix:
                platform:
                    - os-name: Linux-x86_64
                      runs-on: ubuntu-24.04
                      target: x86_64-unknown-linux-musl

                    - os-name: Linux-aarch64
                      runs-on: ubuntu-24.04
                      target: aarch64-unknown-linux-musl

                    - os-name: Linux-riscv64
                      runs-on: ubuntu-24.04
                      target: riscv64gc-unknown-linux-gnu

                    - os-name: Windows-x86_64
                      runs-on: windows-latest
                      target: x86_64-pc-windows-msvc

                    - os-name: macOS-x86_64
                      runs-on: macOS-latest
                      target: x86_64-apple-darwin

                    # more targets here ...

        runs-on: ${{ matrix.platform.runs-on }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build binary
              uses: houseabsolute/actions-rust-cross@v1
              with:
                  target: ${{ matrix.platform.target }}
                  args: "--locked --release"
                  strip: true
                  toolchain: nightly

            - name: Publish artifacts and release
              uses: houseabsolute/actions-rust-release@v0
              with:
                  executable-name: cloudflare-ddns
                  target: ${{ matrix.platform.target }}

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ vars.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Push to Docker Hub
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ vars.DOCKER_USERNAME }}/cloudflare-ddns:latest
                  platforms: linux/amd64

            - name: Push to Docker Hub
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ vars.DOCKER_USERNAME }}/cloudflare-ddns:latest
                  platforms: linux/arm64/v8
                  build-args: |
                        ARCH=aarch64-unknown-linux-musl
