name: Build and Release
run-name: Build artifacts and docker images for all platforms
on: [push]
jobs:
    build-x86_64-unknown-linux-gnu:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - run: sudo apt-get update && sudo apt-get update
            - run: sudo apt-get install -y libc6
            - uses: dtolnay/rust-toolchain@stable
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - run: sudo cargo install cross --git https://github.com/cross-rs/cross

            - run: sudo cargo build --release
            - name: Push to Docker Hub
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ vars.DOCKER_USERNAME }}/cloudflare-ddns:latest
                  platforms: linux/amd64
            - run: sudo mv target/release/cloudflare-ddns cloudflare-ddns-x86_64-unknown-linux-gnu
            
            - run: sudo cross build --release --target aarch64-unknown-linux-musl
            - name: Push to Docker Hub
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ vars.DOCKER_USERNAME }}/cloudflare-ddns:latest
                  platforms: linux/arm64/v8
            - run: sudo mv target/aarch64-unknown-linux-musl/release/cloudflare-ddns cloudflare-ddns-aarch64-unknown-linux-musl


            - run: sudo cross build --release --target x86_64-pc-windows-gnu
            - run: sudo mv target/x86_64-pc-windows-gnu/release/cloudflare-ddns.exe cloudflare-ddns-x86_64-pc-windows-gnu.exe


            - name: Release to GitHub
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      cloudflare-ddns-x86_64-unknown-linux-gnu
                      cloudflare-ddns-aarch64-unknown-linux-musl
                      cloudflare-ddns-x86_64-pc-windows-gnu.exe
                  draft: false
                  prerelease: true
