name: Build for x86-64
run-name: Build for x86-64
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - run: cargo build --release
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Push to Docker Hub
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ vars.DOCKER_USERNAME }}/cloudflare-ddns:latest
                  platforms: linux/amd64